give @s adv:bucket_adv_catfish
give @s adv:bucket_pike
give @s adv:bucket_explosive_crucian
give @s adv:bucket_sandy_bass
give @s adv:bucket_golden_koi
give @s adv:bucket_sunfish
give @s adv:bucket_angelfish
give @s adv:bucket_adv_jellyfish
give @s adv:bucket_sponge_eater
give @s adv:bucket_snowy_walleye
give @s adv:bucket_frost_minnow
give @s adv:bucket_glacier_anchovy
give @s adv:bucket_abyssal_lurker
give @s adv:bucket_angler_fish
give @s adv:bucket_adv_piranha
give @s adv:bucket_sparkling_eel
give @s adv:bucket_mandarinfish
give @s adv:bucket_brown_shroomfin
give @s adv:bucket_red_shroomfin
give @s adv:bucket_ruffe
give @s adv:bucket_mud_tuna
give @s adv:bucket_specular_snapper
give @s adv:bucket_cave_trout
give @s adv:bucket_charged_bullhead
give @s adv:bucket_crystal_mullet
give @s adv:bucket_green_jellyfish
give @s adv:bucket_bonefish
give @s adv:bucket_spookyfin
give @s adv:bucket_cursed_koi
give @s adv:bucket_magikarp