give @s adv:squid
give @s adv:catfish
give @s adv:pike
give @s adv:explosive_crucian
give @s adv:angelfish
give @s adv:jellyfish
give @s adv:sponge_eater
give @s adv:sandy_bass
give @s adv:golden_koi
give @s adv:sunfish
give @s adv:snowy_walleye
give @s adv:frost_minnow
give @s adv:glacier_anchovy
give @s adv:abyssal_lurker
give @s adv:angler_fish
give @s adv:specular_snapper
give @s adv:cave_trout
give @s adv:crystal_mullet
give @s adv:charged_bullhead
give @s adv:piranha
give @s adv:sparkling_eel
give @s adv:mandarinfish
give @s adv:ruffe
give @s adv:mud_tuna
give @s adv:swamp_plaice
give @s adv:brown_shroomfin
give @s adv:red_shroomfin
give @s adv:ender_shad
give @s adv:pearl_sardine
give @s adv:chorus_koi