give @s azc:neptunium_sword
give @s azc:neptunium_axe
give @s azc:neptunium_pickaxe
give @s azc:neptunium_shovel
give @s azc:neptunium_hoe
give @s azc:neptunium_helmet
give @s azc:neptunium_chestplate
give @s azc:neptunium_leggings
give @s azc:neptunium_boots
give @s azc:neptunium_ingot
give @s azc:neptunium_nugget
give @s azc:neptunium_block
give @s azc:neptunes_bounty