give @s azc:bucket_perch
give @s azc:bucket_bluegill
give @s azc:bucket_smallmouth_bass
give @s azc:bucket_brown_trout
give @s azc:bucket_carp
give @s azc:bucket_gar
give @s azc:bucket_minnow
give @s azc:bucket_muskellunge
give @s azc:bucket_catfish
give @s azc:bucket_synodontis
give @s azc:bucket_boulti
give @s azc:bucket_bayad
give @s azc:bucket_capitaine
give @s azc:bucket_atlantic_herring
give @s azc:bucket_blackfish
give @s azc:bucket_pollock
give @s azc:bucket_pink_salmon
give @s azc:bucket_rainbow_trout
give @s azc:bucket_atlantic_cod
give @s azc:bucket_pacific_halibut
give @s azc:bucket_atlantic_halibut
give @s azc:bucket_red_grouper
give @s azc:bucket_azc_squid
give @s azc:bucket_jellyfish
give @s azc:bucket_tuna
give @s azc:bucket_piranha
give @s azc:bucket_tambaqui
give @s azc:bucket_electric_eel
give @s azc:bucket_arapaima
give @s azc:bucket_arrau_turtle
give @s azc:bucket_box_turtle
give @s azc:bucket_starshell_turtle
give @s azc:bucket_red_shrooma
give @s azc:bucket_brown_shrooma
give @s azc:bucket_goldfish