fill ~~~ ~~~ stripped_oak_log 0 replace log 0
fill ~~~ ~~~ stripped_spruce_log 0 replace log 1
fill ~~~ ~~~ stripped_birch_log 0 replace log 2
fill ~~~ ~~~ stripped_jungle_log 0 replace log 3
fill ~~~ ~~~ stripped_acacia_log 0 replace log2 0
fill ~~~ ~~~ stripped_dark_oak_log 0 replace log2 1
fill ~~~ ~~~ stripped_mangrove_log 0 replace mangrove_log 0
fill ~~~ ~~~ stripped_crimson_stem 0 replace crimson_stem 0
fill ~~~ ~~~ stripped_warped_stem 0 replace warped_stem 0