give @s azc:sashimi
give @s azc:cooked_fish_fillet
give @s azc:cooked_frog_legs
give @s azc:algae
give @s azc:seaweed
give @s azc:sushi
give @s azc:turtle_soup
give @s azc:raw_whale_steak
give @s azc:cooked_whale_steak
give @s azc:whale_burger