execute @s ~ ~ ~ detect ~1 ~ ~ lava 0 tag @s add powered
execute @s ~ ~ ~ detect ~1 ~ ~ lava 1 tag @s add powered
execute @s ~ ~ ~ detect ~1 ~ ~ lava 2 tag @s add powered
execute @s ~ ~ ~ detect ~1 ~ ~ lava 3 tag @s add powered
execute @s ~ ~ ~ detect ~1 ~ ~ lava 4 tag @s add powered
execute @s ~ ~ ~ detect ~1 ~ ~ lava 5 tag @s add powered
execute @s ~ ~ ~ detect ~1 ~ ~ lava 6 tag @s add powered
execute @s ~ ~ ~ detect ~1 ~ ~ lava 7 tag @s add powered
execute @s ~ ~ ~ detect ~1 ~ ~ lava 8 tag @s add powered
execute @s ~ ~ ~ detect ~1 ~ ~ lava 9 tag @s add powered
execute @s ~ ~ ~ detect ~1 ~ ~ lava 10 tag @s add powered
execute @s ~ ~ ~ detect ~1 ~ ~ lava 11 tag @s add powered
execute @s ~ ~ ~ detect ~1 ~ ~ lava 12 tag @s add powered 
execute @s ~ ~ ~ detect ~1 ~ ~ lava 13 tag @s add powered
execute @s ~ ~ ~ detect ~1 ~ ~ lava 14 tag @s add powered
execute @s ~ ~ ~ detect ~1 ~ ~ lava 15 tag @s add powered