give @s adv:green_jellyfish
give @s adv:bonefish
give @s adv:spookyfin
give @s adv:cursed_koi
give @s adv:obsidian_bream
give @s adv:nether_sturgeon
give @s adv:magma_jellyfish
give @s adv:withered_crucian
give @s adv:quartz_chub
give @s adv:fungi_catfish
give @s adv:flarefin_koi
give @s adv:blaze_pike
give @s adv:magikarp
give @s adv:blazing_fishing_pole