execute @a[hasitem={location=slot.armor.head,item=oh:titanium_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:titanium_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:titanium_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:titanium_boots}] ~ ~ ~ effect @s fire_resistance 2 0 true
execute @a[hasitem={location=slot.armor.head,item=oh:titanium_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:titanium_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:titanium_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:titanium_boots}] ~ ~ ~ effect @s strength 2 1 true
execute @a[hasitem={location=slot.armor.head,item=oh:titanium_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:titanium_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:titanium_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:titanium_boots}] ~ ~ ~ effect @s resistance 2 1 true

execute @a[hasitem={location=slot.armor.head,item=oh:orichalcum_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:orichalcum_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:orichalcum_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:orichalcum_boots}] ~ ~ ~ effect @s fire_resistance 2 0 true
execute @a[hasitem={location=slot.armor.head,item=oh:orichalcum_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:orichalcum_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:orichalcum_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:orichalcum_boots}] ~ ~ ~ effect @s strength 2 0 true
execute @a[hasitem={location=slot.armor.head,item=oh:orichalcum_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:orichalcum_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:orichalcum_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:orichalcum_boots}] ~ ~ ~ effect @s resistance 2 1 true
execute @a[hasitem={location=slot.armor.head,item=oh:orichalcum_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:orichalcum_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:orichalcum_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:orichalcum_boots}] ~ ~ ~ effect @s speed 2 0 true

execute @a[hasitem={location=slot.armor.head,item=oh:tin_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:tin_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:tin_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:tin_boots}] ~ ~ ~ effect @s resistance 2 0 true
execute @a[hasitem={location=slot.armor.head,item=oh:tin_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:tin_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:tin_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:tin_boots}] ~ ~ ~ effect @s strength 2 0 true

execute @a[hasitem={location=slot.armor.head,item=oh:topaz_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:topaz_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:topaz_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:topaz_boots}] ~ ~ ~ effect @s resistance 2 0 true
execute @a[hasitem={location=slot.armor.head,item=oh:topaz_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:topaz_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:topaz_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:topaz_boots}] ~ ~ ~ effect @s strength 2 0 true

execute @a[hasitem={location=slot.armor.head,item=oh:bronce_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:bronce_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:bronce_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:bronce_boots}] ~ ~ ~ effect @s resistance 2 1 true

execute @a[hasitem={location=slot.armor.head,item=oh:ruby_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:ruby_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:ruby_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:ruby_boots}] ~ ~ ~ effect @s strength 2 0 true
execute @a[hasitem={location=slot.armor.head,item=oh:ruby_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:ruby_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:ruby_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:ruby_boots}] ~ ~ ~ effect @s resistance 2 0 true

execute @a[hasitem={location=slot.armor.head,item=oh:jade_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:jade_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:jade_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:jade_boots}] ~ ~ ~ effect @s village_hero 2 0 true
execute @a[hasitem={location=slot.armor.head,item=oh:jade_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:jade_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:jade_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:jade_boots}] ~ ~ ~ effect @s resistance 2 0 true
execute @a[hasitem={location=slot.armor.head,item=oh:jade_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:jade_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:jade_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:jade_boots}] ~ ~ ~ effect @s jump_boost 2 0 true

execute @a[hasitem={location=slot.armor.head,item=oh:migtinio_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:migtinio_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:migtinio_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:migtinio_boots}] ~ ~ ~ effect @s strength 2 0 true
execute @a[hasitem={location=slot.armor.head,item=oh:migtinio_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:migtinio_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:migtinio_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:migtinio_boots}] ~ ~ ~ effect @s resistance 2 1 true

execute @a[hasitem={location=slot.armor.head,item=oh:platinum_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:platinum_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:platinum_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:platinum_boots}] ~ ~ ~ effect @s resistance 2 1 true
execute @a[hasitem={location=slot.armor.head,item=oh:platinum_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:platinum_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:platinum_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:platinum_boots}] ~ ~ ~ effect @s strength 2 0 true

execute @a[hasitem={location=slot.armor.head,item=oh:paladium_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:paladium_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:paladium_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:paladium_boots}] ~ ~ ~ effect @s strength 2 1 true
execute @a[hasitem={location=slot.armor.head,item=oh:paladium_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:paladium_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:paladium_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:paladium_boots}] ~ ~ ~ effect @s resistance 2 1 true

execute @a[hasitem={location=slot.armor.head,item=oh:mithril_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:mithril_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:mithril_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:mithril_boots}] ~ ~ ~ effect @s resistance 2 0 true
execute @a[hasitem={location=slot.armor.head,item=oh:mithril_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:mithril_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:mithril_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:mithril_boots}] ~ ~ ~ effect @s strength 2 0 true

execute @a[hasitem={location=slot.armor.head,item=oh:onyx_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:onyx_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:onyx_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:onyx_boots}] ~ ~ ~ effect @s fire_resistance 2 0 true
execute @a[hasitem={location=slot.armor.head,item=oh:onyx_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:onyx_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:onyx_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:onyx_boots}] ~ ~ ~ effect @s resistance 2 0 true
execute @a[hasitem={location=slot.armor.head,item=oh:onyx_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:onyx_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:onyx_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:onyx_boots}] ~ ~ ~ effect @s night_vision 11 0 true

execute @a[hasitem={location=slot.armor.head,item=oh:tourmaline_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:tourmaline_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:tourmaline_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:tourmaline_boots}] ~ ~ ~ effect @s conduit_power 2 0 true
execute @a[hasitem={location=slot.armor.head,item=oh:tourmaline_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:tourmaline_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:tourmaline_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:tourmaline_boots}] ~ ~ ~ effect @s resistance 2 0 true
execute @a[hasitem={location=slot.armor.head,item=oh:tourmaline_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:tourmaline_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:tourmaline_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:tourmaline_boots}] ~ ~ ~ effect @s haste 2 0 true

execute @a[hasitem={location=slot.armor.head,item=oh:cobalto_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:cobalto_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:cobalto_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:cobalto_boots}] ~ ~ ~ effect @s resistance 2 1 true
execute @a[hasitem={location=slot.armor.head,item=oh:cobalto_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:cobalto_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:cobalto_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:cobalto_boots}] ~ ~ ~ effect @s strength 2 0 true
execute @a[hasitem={location=slot.armor.head,item=oh:cobalto_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:cobalto_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:cobalto_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:cobalto_boots}] ~ ~ ~ effect @s fire_resistance 2 0 true 

execute @a[hasitem={location=slot.armor.head,item=oh:adamantite_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:adamantite_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:adamantite_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:adamantite_boots}] ~ ~ ~ effect @s resistance 2 1 true
execute @a[hasitem={location=slot.armor.head,item=oh:adamantite_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:adamantite_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:adamantite_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:adamantite_boots}] ~ ~ ~ effect @s strength 2 1 true
execute @a[hasitem={location=slot.armor.head,item=oh:adamantite_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:adamantite_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:adamantite_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:adamantite_boots}] ~ ~ ~ effect @s fire_resistance 2 0 true
execute @a[hasitem={location=slot.armor.head,item=oh:adamantite_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:adamantite_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:adamantite_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:adamantite_boots}] ~ ~ ~ effect @s night_vision 11 0 true

execute @a[hasitem={location=slot.armor.head,item=oh:enderite_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:enderite_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:enderite_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:enderite_boots}] ~ ~ ~ effect @s jump_boost 2 0 true
execute @a[hasitem={location=slot.armor.head,item=oh:enderite_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:enderite_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:enderite_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:enderite_boots}] ~ ~ ~ effect @s regeneration 2 1 true
execute @a[hasitem={location=slot.armor.head,item=oh:enderite_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:enderite_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:enderite_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:enderite_boots}] ~ ~ ~ effect @s strength 2 2 true
execute @a[hasitem={location=slot.armor.head,item=oh:enderite_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:enderite_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:enderite_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:enderite_boots}] ~ ~ ~ effect @s resistance 2 2 true
execute @a[hasitem={location=slot.armor.head,item=oh:enderite_helmet}] ~ ~ ~ execute @a[hasitem={location=slot.armor.chest,item=oh:enderite_chestplate}] ~ ~ ~ execute @a[hasitem={location=slot.armor.legs,item=oh:enderite_leggings}] ~ ~ ~ execute @a[hasitem={location=slot.armor.feet,item=oh:enderite_boots}] ~ ~ ~ effect @s fire_resistance 2 2 true