give @s azc:wooden_fishing_rod_template
give @s azc:iron_fishing_rod_template
give @s azc:golden_fishing_rod_template
give @s azc:diamond_fishing_rod_template
give @s azc:neptunium_fishing_rod_template
give @s minecraft:fishing_rod
give @s azc:iron_fishing_rod_usual
give @s azc:golden_fishing_rod_usual
give @s azc:diamond_fishing_rod_usual
give @s azc:neptunium_fishing_rod_usual
give @s azc:wooden_fishing_rod_double
give @s azc:iron_fishing_rod_double
give @s azc:golden_fishing_rod_double
give @s azc:diamond_fishing_rod_double
give @s azc:neptunium_fishing_rod_double
give @s azc:wooden_fishing_rod_golden
give @s azc:iron_fishing_rod_golden
give @s azc:golden_fishing_rod_golden
give @s azc:diamond_fishing_rod_golden
give @s azc:neptunium_fishing_rod_golden
give @s azc:wooden_fishing_rod_redstone
give @s azc:iron_fishing_rod_redstone
give @s azc:golden_fishing_rod_redstone
give @s azc:diamond_fishing_rod_redstone
give @s azc:neptunium_fishing_rod_redstone
give @s azc:neptunium_fishing_rod_nether_star