give @s azc:driftwood
give @s azc:tin_can
give @s azc:fish_bones
give @s azc:goldfish
give @s azc:box
give @s azc:lockbox
give @s azc:treasure_chest
give @s azc:message_in_a_bottle
give @s azc:wooden_fillet_knife
give @s azc:stone_fillet_knife
give @s azc:iron_fillet_knife
give @s azc:golden_fillet_knife
give @s azc:diamond_fillet_knife
give @s azc:neptunium_fillet_knife
give @s azc:bobber
give @s azc:fishing_line
give @s azc:iron_hook
give @s azc:double_iron_hook
give @s azc:golden_hook
give @s azc:redstone_hook
give @s azc:nether_star_hook
give @s azc:tackle_box
give @s azc:minnow
give @s azc:leech
give @s azc:worm
give @s azc:wooden_fish_trap
give @s azc:iron_fish_trap
give @s azc:golden_fish_trap
give @s azc:redstone_fish_trap
give @s azc:worm_farm