give @s azc:box_gravel
give @s azc:box_cobblestone
give @s azc:box_rotten_flesh
give @s azc:box_flint
give @s azc:box_clay_ball
give @s azc:box_leather
give @s azc:box_feather
give @s azc:box_coal
give @s azc:box_charcoal
give @s azc:box_wheat_seeds
give @s azc:box_bowl
give @s azc:box_string
give @s azc:box_leather_helmet
give @s azc:box_leather_chestplate
give @s azc:box_leather_leggings
give @s azc:box_leather_boots
give @s azc:box_stone
give @s azc:box_dirt
give @s azc:box_bucket
give @s azc:box_slime_ball
give @s azc:box_sugar_cane
give @s azc:box_glass_bottle
give @s azc:box_carrot
give @s azc:box_potato
give @s azc:box_vine
give @s azc:box_apple