give @s azc:perch
give @s azc:bluegill
give @s azc:smallmouth_bass
give @s azc:brown_trout
give @s azc:carp
give @s azc:gar
give @s azc:muskellunge
give @s azc:azc_catfish
give @s azc:synodontis
give @s azc:boulti
give @s azc:bayad
give @s azc:capitaine
give @s azc:atlantic_herring
give @s azc:blackfish
give @s azc:pollock
give @s azc:pink_salmon
give @s azc:rainbow_trout
give @s azc:atlantic_cod
give @s azc:pacific_halibut
give @s azc:atlantic_halibut
give @s azc:azc_squid
give @s azc:azc_jellyfish
give @s azc:red_grouper
give @s azc:swordfish
give @s azc:shark
give @s azc:tuna
give @s azc:whale